const crypto = require('node:crypto');

function text(value) { return String(value || '').trim().replace(/\s+/g, ' '); }
function domain(value) { const candidate = text(value).replace(/^https?:\/\//i, '').split('/')[0].toLowerCase(); if (!candidate) return ''; if (!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$/i.test(candidate)) throw new Error('Company domain must be a valid hostname.'); return candidate; }
function normalizeProspect(input = {}) { const name = text(input.name); if (!name) throw new Error('Name is required.'); const parts = name.split(' '); return { name, firstName: parts[0].toLowerCase(), lastName: (parts.at(-1) || '').toLowerCase(), company: text(input.company), title: text(input.title), domain: domain(input.domain), profileUrl: text(input.profileUrl), importedEmail: text(input.importedEmail || input.email || input.workEmail), importedPhone: text(input.importedPhone || input.phone || input.businessPhone) }; }
function candidate(firstName, lastName, host) { if (!host || !firstName || !lastName) return []; return [`${firstName}.${lastName}@${host}`, `${firstName[0]}${lastName}@${host}`]; }
function id(result) { return crypto.createHash('sha256').update(`${result.value}|${result.sourceUrl || ''}`).digest('hex').slice(0, 16); }
function make(value, contactType, status, confidence, reason, sourceUrl = '') { const labels = { pattern_candidate: 'Pattern candidate — not verified', publicly_found: 'Publicly found', provider_verified: 'Provider verified', recruiter_imported: 'Recruiter imported' }; return { id: id({ value, sourceUrl }), value, contactType, status, statusLabel: labels[status] || status, confidence, reason, sourceUrl, retrievedAt: new Date().toISOString() }; }
function policyAllows(host, limits) { const now = Date.now(); const last = limits.get(host) || 0; if (now - last < 1000) return false; limits.set(host, now); return true; }
async function robotsAllows(url) { const root = new URL(url); const robots = new URL('/robots.txt', root).toString(); try { const response = await fetch(robots, { signal: AbortSignal.timeout(4000), redirect: 'error' }); if (!response.ok) return false; const body = await response.text(); const generic = body.match(/User-agent:\s*\*([\s\S]*?)(?=\nUser-agent:|$)/i)?.[1] || ''; const rules = generic.split(/\r?\n/).map((line) => line.match(/^\s*(allow|disallow):\s*(\S*)/i)).filter(Boolean).map((match) => ({ kind: match[1].toLowerCase(), path: match[2] })); const matching = rules.filter((rule) => rule.path && root.pathname.startsWith(rule.path)).sort((a, b) => b.path.length - a.path.length)[0]; return !matching || matching.kind === 'allow'; } catch { return false; } }
async function publicCompanyPage(prospect, limits) { if (!prospect.domain || !policyAllows(prospect.domain, limits)) return []; const url = `https://${prospect.domain}/contact`;
  if (!(await robotsAllows(url))) return [];
  try { const response = await fetch(url, { signal: AbortSignal.timeout(5000), redirect: 'error', headers: { 'user-agent': 'findEmm/0.1 permitted-company-page lookup' } }); if (!response.ok || !/^text\/html/.test(response.headers.get('content-type') || '')) return []; const page = (await response.text()).slice(0, 300_000); const emails = [...new Set(page.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi) || [])].filter((email) => email.toLowerCase().endsWith(`@${prospect.domain}`)).slice(0, 5); const phones = [...new Set(page.match(/\+?[0-9][0-9 ()-]{7,}[0-9]/g) || [])].slice(0, 3); return [...emails.map((value) => make(value, 'work_email', 'publicly_found', 85, 'Found on permitted company contact page.', url)), ...phones.map((value) => make(value, 'business_phone', 'publicly_found', 70, 'Found on permitted company contact page; confirm ownership before contact.', url))]; } catch { return []; } }
const sourceRegistry = Object.freeze([
  { id: 'recruiter-import', permission: 'recruiter-supplied local data', rateLimit: 'none' },
  { id: 'company-contact-page', permission: 'public company page allowed by robots policy', rateLimit: 'one request per host per second' },
  { id: 'provider-adapter', permission: 'opt-in provider API with recruiter authorization', rateLimit: 'provider contract; adapter required' }
]);
async function enrich(prospect, limits) { const imported = [prospect.importedEmail && make(prospect.importedEmail, 'work_email', 'recruiter_imported', 100, 'Provided by recruiter; independently verify before outreach.'), prospect.importedPhone && make(prospect.importedPhone, 'business_phone', 'recruiter_imported', 100, 'Provided by recruiter; independently verify before outreach.')].filter(Boolean); const publicResults = await publicCompanyPage(prospect, limits); const patterns = [...imported, ...publicResults].some((result) => result.contactType === 'work_email') ? [] : candidate(prospect.firstName, prospect.lastName, prospect.domain).map((value) => make(value, 'work_email', 'pattern_candidate', 35, 'Common company pattern derived from supplied name and domain. Not verified.')); return [...imported, ...publicResults, ...patterns].filter((result, index, list) => list.findIndex((other) => other.id === result.id) === index); }
function newBatch(prospects, results) { return prospects.map((prospect, index) => ({ prospect: normalizeProspect(prospect), results: results[index] })); }
module.exports = { normalizeProspect, enrich, newBatch, policyAllows, sourceRegistry };
